package com.adyen.services.customfields;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Feb 13 12:35:42 EET 2009
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://customfields.services.adyen.com", name = "CustomFieldsPortType")
@XmlSeeAlso({com.adyen.services.common.ObjectFactory.class,ObjectFactory.class})
public interface CustomFieldsPortType {

    @WebResult(name = "customFieldResponse", targetNamespace = "http://customfields.services.adyen.com")
    @RequestWrapper(localName = "check", targetNamespace = "http://customfields.services.adyen.com", className = "com.adyen.services.customfields.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://customfields.services.adyen.com", className = "com.adyen.services.customfields.CheckResponse")
    @WebMethod
    public com.adyen.services.customfields.CustomFieldResponse check(
        @WebParam(name = "customFieldRequest", targetNamespace = "http://customfields.services.adyen.com")
        com.adyen.services.customfields.CustomFieldRequest customFieldRequest
    ) throws ServiceException;
}
