
package com.adyen.services.customfields;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.4
 * Fri Feb 13 12:35:42 EET 2009
 * Generated source version: 2.1.4
 * 
 */

@WebFault(name = "ServiceException", targetNamespace = "http://customfields.services.adyen.com")
public class ServiceException extends Exception {
    public static final long serialVersionUID = 20090213123542L;
    
    private com.adyen.services.common.ServiceException serviceException;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, com.adyen.services.common.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException(String message, com.adyen.services.common.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public com.adyen.services.common.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
